spring.application.name=spring-demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ProductDB;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa

spring.datasource.password=HEMANTHsai@2005

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none